# Generated by Django 5.2.7 on 2025-12-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock'), ('aquaculture', 'Aquaculture')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('treatment', models.TextField()),
                ('preventive_measures', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
